[pytest]
python_files = test_*.py **/test*/**/__init__.py  # TODO: remove Test* once all worlds have been ported
python_classes = Test
python_functions = test
testpaths =
    test
    worlds
norecursedirs =
    worlds/albw
    worlds/animal_well
    worlds/anodyne
    worlds/archipidle
    worlds/autopelago
    worlds/axiomverge
    worlds/balatro
    worlds/banjo_tooie
    worlds/Bingo
    worlds/bomberman_tsa
    worlds/borderlands2
    worlds/cat_quest
    worlds/celeste
    worlds/crosscode
    worlds/crystal_project
    worlds/ctjot
    worlds/dc1
    worlds/dc2
    worlds/diddy_kong_racing
    worlds/dk64
    worlds/dkc
    worlds/dkc2
    worlds/dragon_warrior
    worlds/dw1
    worlds/earthbound
    worlds/enter_the_gungeon
    worlds/fe8
    worlds/ff1pr
    worlds/ff4fe
    worlds/ff6wc
    worlds/ff12_open_world
    worlds/ffta
    worlds/fftii
    worlds/ffvcd
    worlds/fm
    worlds/hades
    worlds/jigsaw
    worlds/k64
    worlds/keymasters_keep
    worlds/khbbs
    worlds/khrecom
    worlds/kss
    worlds/ladx_beta
    worlds/lrff13
    worlds/mario_kart_double_dash
    worlds/melee
    worlds/metroidfusion
    worlds/metroidprime
    worlds/mindustry
    worlds/minishoot
    worlds/minit
    worlds/mm_recomp
    worlds/mmx
    worlds/mmx2
    worlds/mmx3
    worlds/oot_soh
    worlds/openrct2
    worlds/osu
    worlds/outer_wilds
    worlds/pharcryption
    worlds/plateup
    worlds/pokemon_bw
    worlds/pokemon_crystal
    worlds/pokemon_frlg
    worlds/pokemon_platinum
    worlds/prodigal
    worlds/pseudoregalia
    worlds/RAC1
    worlds/rac2
    worlds/rac3
    worlds/rogue_legacy
    worlds/rotn
    worlds/sadv2
    worlds/sadx
    worlds/satisfactory
    worlds/shadow_the_hedgehog
    worlds/shahrazad
    worlds/shapez_2
    worlds/sm_map_rando
    worlds/smrpg
    worlds/spelunky2
    worlds/spire
    worlds/spyro2
    worlds/spyro3
    worlds/ss
    worlds/subversion
    worlds/tboir
    worlds/tcg_card_shop_simulator
    worlds/tloz_ooa
    worlds/tloz_oos
    worlds/tloz_ph
    worlds/tmc
    worlds/twistycube
    worlds/wargroove2
    worlds/waterywords
    worlds/wordipelago
    worlds/zelda2

