[pytest]
python_files = test_*.py **/test*/**/__init__.py  # TODO: remove Test* once all worlds have been ported
python_classes = Test
python_functions = test
testpaths =
    test
    worlds
addopts =
    --ignore=worlds/albw
    --ignore=worlds/animal_well
    --ignore=worlds/anodyne
    --ignore=worlds/archipidle
    --ignore=worlds/autopelago
    --ignore=worlds/axiomverge
    --ignore=worlds/balatro
    --ignore=worlds/banjo_tooie
    --ignore=worlds/Bingo
    --ignore=worlds/bomberman_tsa
    --ignore=worlds/borderlands2
    --ignore=worlds/cat_quest
    --ignore=worlds/celeste
    --ignore=worlds/crosscode
    --ignore=worlds/crystal_project
    --ignore=worlds/ctjot
    --ignore=worlds/dc1
    --ignore=worlds/dc2
    --ignore=worlds/diddy_kong_racing
    --ignore=worlds/dk64
    --ignore=worlds/dkc
    --ignore=worlds/dkc2
    --ignore=worlds/dragon_warrior
    --ignore=worlds/dw1
    --ignore=worlds/earthbound
    --ignore=worlds/enter_the_gungeon
    --ignore=worlds/fe8
    --ignore=worlds/ff1pr
    --ignore=worlds/ff4fe
    --ignore=worlds/ff6wc
    --ignore=worlds/ff12_open_world
    --ignore=worlds/ffta
    --ignore=worlds/fftii
    --ignore=worlds/ffvcd
    --ignore=worlds/fm
    --ignore=worlds/hades
    --ignore=worlds/jigsaw
    --ignore=worlds/k64
    --ignore=worlds/keymasters_keep
    --ignore=worlds/khbbs
    --ignore=worlds/khrecom
    --ignore=worlds/kss
    --ignore=worlds/ladx_beta
    --ignore=worlds/lrff13
    --ignore=worlds/mario_kart_double_dash
    --ignore=worlds/melee
    --ignore=worlds/metroidfusion
    --ignore=worlds/metroidprime
    --ignore=worlds/mindustry
    --ignore=worlds/minishoot
    --ignore=worlds/minit
    --ignore=worlds/mm_recomp
    --ignore=worlds/mmx
    --ignore=worlds/mmx2
    --ignore=worlds/mmx3
    --ignore=worlds/oot_soh
    --ignore=worlds/openrct2
    --ignore=worlds/osu
    --ignore=worlds/outer_wilds
    --ignore=worlds/pharcryption
    --ignore=worlds/plateup
    --ignore=worlds/pokemon_bw
    --ignore=worlds/pokemon_crystal
    --ignore=worlds/pokemon_frlg
    --ignore=worlds/pokemon_platinum
    --ignore=worlds/prodigal
    --ignore=worlds/pseudoregalia
    --ignore=worlds/RAC1
    --ignore=worlds/rac2
    --ignore=worlds/rac3
    --ignore=worlds/rogue_legacy
    --ignore=worlds/rotn
    --ignore=worlds/sadv2
    --ignore=worlds/sadx
    --ignore=worlds/satisfactory
    --ignore=worlds/shadow_the_hedgehog
    --ignore=worlds/shahrazad
    --ignore=worlds/shapez_2
    --ignore=worlds/sm_map_rando
    --ignore=worlds/smrpg
    --ignore=worlds/spelunky2
    --ignore=worlds/spire
    --ignore=worlds/spyro2
    --ignore=worlds/spyro3
    --ignore=worlds/ss
    --ignore=worlds/subversion
    --ignore=worlds/tboir
    --ignore=worlds/tcg_card_shop_simulator
    --ignore=worlds/tloz_ooa
    --ignore=worlds/tloz_oos
    --ignore=worlds/tloz_ph
    --ignore=worlds/tmc
    --ignore=worlds/twistycube
    --ignore=worlds/wargroove2
    --ignore=worlds/waterywords
    --ignore=worlds/wordipelago
    --ignore=worlds/zelda2
